apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-warehouse-backend-media-pv
  labels:
    app.kubernetes.io/name: my-warehouse-backend-media
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-zfs
  nfs:
    server: 192.168.11.16
    path: /srv/nfs/kubernetes/my-warehouse-media
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-warehouse-backend-media
  namespace: my-warehouse
  labels:
    app.kubernetes.io/name: my-warehouse-backend-media
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  volumeName: my-warehouse-backend-media-pv
